# Generated by Django 5.1.2 on 2024-11-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hall',
        ),
    ]
